#!/usr/bin/env bash
# Installs a git pre-commit hook that warns (does NOT block) when a pure-algorithm
# test changes on only one side of the TypeScript ⇄ Kotlin pair.
#
# Usage: npm run hooks:install   (idempotent, safe to re-run)
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
hooks_dir="$repo_root/.git/hooks"
hook_file="$hooks_dir/pre-commit"

mkdir -p "$hooks_dir"

cat > "$hook_file" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit by hand.
# Warns (does not block) about unpaired core-test changes. Re-create with:
#   npm run hooks:install
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
if [ -f "$repo_root/package.json" ] && command -v node >/dev/null 2>&1; then
  (cd "$repo_root" && npm run --silent core:sync-check >/dev/null 2>&1) \
    || echo "⚠ Recordatorio: revisa la sincronización de tests del core (npm run core:sync-check)."
fi
exit 0
EOF

chmod +x "$hook_file"
echo "✔ Hook pre-commit instalado en $hook_file (avisa, no bloquea)."
